const ENV_CONFIG = {
    API_KEY: "XXXXXXXXXXX",
    AUTH_DOMAIN: "XXXXXXXX",
    PROJECT_ID: "XXXXXXXX",
    STORAGE_BUCKET: "XXXXXXXX",
    MESSAGING_SENDER_ID: "XXXXXXXX",
    APP_ID: "XXXXXX",
    MEASUREMENT_ID: "XXXXXX"
}

export default ENV_CONFIG;